### ISSUE TITLE
Please remove pdf of the book

### ISSUE THREAD

**Issue by wsvincent** [Badhansen/django001#1]
Hi, 

I'm the author of the book. This is how I make my living and it's also how I can manage to do updates and maintain all the other things I do for free in the Django community.

Please remove the pdf from the repo. It's fine to share the code and I encourage people to talk about their work.

**Comment by Badhansen** [comment]
Hi @wsvincent,
Thank you for reaching out. I appreciate your support for the Django community. I'll remove the PDF from the repository while keeping the code available for sharing and discussion.

And I apologize for any inconvenience.

Best regards,
Badhan Sen.

**Comment by wsvincent** [comment]
Thank you.

**Comment by Badhansen** [comment]
Hi @wsvincent, 
I have removed book the, and thank you for your contribution to the community.
Thanks
